image: python:3.9

pipelines:
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel twine
                    - tox -e py39
                    - ./deploy.bash
